database:
  name: 'smsr'
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432

sqlalchemy:
  echo: false
  track_modifications: false

pooling:
  max_overflow: 10
  pool_size: 5
  pool_timeout: 30
  pool_recycle: 3600

tables:
  - name: 'Proprietes'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Type'
        type: 'String'
      - name: 'Ville'
        type: 'String'
      - name: 'Quartier'
        type: 'String'
      - name: 'Prix'
        type: 'Float'
      - name: 'DatePublication'
        type: 'DateTime'
      - name: 'URLImage'
        type: 'String'
      - name: 'NombreImages'
        type: 'Integer'
      - name: 'NombreChambres'
        type: 'Integer'
      - name: 'NombreSalons'
        type: 'Integer'
      - name: 'NombreSallesBain'
        type: 'Integer'
      - name: 'NumeroEtage'
        type: 'Integer'
      - name: 'SurfaceHabitable'
        type: 'Float'
      - name: 'SurfaceTotale'
        type: 'Float'
      - name: 'AgePropriete'
        type: 'Integer'
      - name: 'URLAnnonce'
        type: 'String'
        unique: true
      - name: 'Images'
        type: 'String'
      - name: 'Etat'
        type: 'String'
        default: 'New'
        
  - name: 'Villes'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Nom'
        type: 'String'
  - name: 'Quartiers'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Nom'
        type: 'String'
      - name: 'IDVille'
        type: 'Integer'
        foreign_key: 'Villes.ID'
  - name: 'Etablissements'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Nom'
        type: 'String'
      - name: 'Type'
        type: 'String'
      - name: 'Evaluation'
        type: 'Float'
      - name: 'IDQuartier'
        type: 'Integer'
        foreign_key: 'Quartiers.ID'
  - name: 'Avis'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Sentiment'
        type: 'String'
      - name: 'Texte'
        type: 'String'
      - name: 'IDEtablissement'
        type: 'Integer'
        foreign_key: 'Etablissements.ID'
  - name: 'ArticlesPresse'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Titre'
        type: 'String'
      - name: 'Sentiment'
        type: 'String'
      - name: 'Texte'
        type: 'String'
      - name: 'DatePublication'
        type: 'DateTime'
      - name: 'IDQuartier'   
        type: 'Integer'
        foreign_key: 'Quartiers.ID'
  - name: 'PostsReseauxSociaux'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Sentiment'
        type: 'String'
      - name: 'Texte'
        type: 'String'
      - name: 'DatePublication'
        type: 'DateTime'
      - name: 'IDQuartier'
        type: 'Integer'
        foreign_key: 'Quartiers.ID'
      - name: 'IDVille'
        type: 'Integer'
        foreign_key: 'Villes.ID'
      - name: 'IDEtablissement'
        type: 'Integer'
        foreign_key: 'Etablissements.ID'
      - name: 'IDPropriete'
        type: 'Integer'
        foreign_key: 'Proprietes.ID'
      - name: 'IDArticlePresse'
        type: 'Integer'
        foreign_key: 'ArticlesPresse.ID'
  - name: 'Statistiques'
    columns:
      - name: 'ID'
        type: 'Integer'
        primary_key: true
      - name: 'Date'
        type: 'DateTime'
      - name: 'TypeStatistique'
        type: 'String'
      - name: 'Valeur'
        type: 'Float'
      - name: 'IDVille'
        type: 'Integer'
        foreign_key: 'Villes.ID'
      - name: 'IDQuartier'
        type: 'Integer'
        foreign_key: 'Quartiers.ID'
      - name: 'IDEtablissement'
        type: 'Integer'
        foreign_key: 'Etablissements.ID'
      - name: 'IDPropriete'
        type: 'Integer'
        foreign_key: 'Proprietes.ID'
