base_url: http://localhost:5000/get_record/Propriete
initial_state: init_driver
states:
  init_driver:
    method: init_driver
    next_state: get_properties
  get_properties:
    method: call_api
    next_state: get_link_data
    parameters:
      api_url: http://localhost:5000/get_record/Proprietes
      params:
        limit: 1
  get_link_data:
    method: get_data
    next_state: goto_link
    parameters:
      source: step_results
      get:
        - ['key', 'get_properties']
        - ['key', 'records']
        - ['index', 0]
        - ['key', 'URLAnnonce']
  goto_link:
    method: goto_link
    next_state: scrap_page
    parameters:
      link: "{previous_result}"
  scrap_page:
    method: scrap_page
    parameters:
      by_method: 'CSS_SELECTOR'
      value: 'body'
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
