base_url: https://wololo.net/page/{i}/
initial_state: goto_next_page
states:
  extract_data:
    method: extract_data
    next_state: send_data
    parameters:
      raw_data: '{previous_result}'
      selectors:
      - attrs:
          class: post-title
        name: h2
  goto_next_page:
    method: goto_next_page
    next_state: scrap_page
    parameters:
      base_url: https://wololo.net/page/{i}/
      next_page: 280
  scrap_page:
    method: scrap_page
    next_state: extract_data
    parameters:
      by_method: CSS_SELECTOR
      value: div.post-list.group
  send_data:
    method: send_data
    next_state: goto_next_page
    parameters:
      address: http://127.0.0.1:5000/api/receive_dict
      data: '{previous_result}'
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/88.0.4324.150 Safari/537.36
